name: wastat_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.5+1

  # Local Storage
  shared_preferences: ^2.5.4

  # Database
  sqflite: ^2.4.2
  path: ^1.9.1

  # Charts
  fl_chart: ^1.2.0

  # Notifications
  flutter_local_notifications: ^21.0.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  flutter_animate: ^4.5.2
  intl: ^0.20.2

  # Permissions
  permission_handler: ^12.0.1

  # UUID
  uuid: ^4.5.3

  # Bridge connection
  web_socket_channel: ^3.0.3
  qr_flutter: ^4.1.0
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0

  # Background foreground service
  flutter_foreground_task: ^9.2.1

  flutter_contacts_service: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
